options:
  doRGBtoGRBfix: false
  beat-increment-amount: 1 #each time KEY_FASTER_BEAT or KEY_SLOWER_BEAT is hit, increase the tempo by this amount of the original
general-keybinds:
  KEY_DO_BEAT: b
  KEY_TOGGLE_BEAT: v
  KEY_HALF_TEMPO: n
  KEY_DOUBLE_TEMPO: m
  KEY_SLOWER_BEAT: ','
color-names:
  WHITE: FFFFFF
  PINK: FFC3C3
  RED: FF0000
  ORANGE: FF7F00
  GOLD: FFDA00
  YELLOW: FFFF00
  GREEN: 00FF00
  TEAL: 00FFC3
  SKY: 00DDFF
  BLUE: 0000FF
  VIOLET: 4B0082
  PURPLE: 9400D3
color-keybinds: #Not yet implemented... probably never will be... ignore this section
  q: RANDOM
  w: WHITE
  e: PINK
  r: RED
  t: ORANGE
  y: GOLD
  u: YELLOW
  i: GREEN
  o: TEAL
  p: SKY
  ']': BLUE
  '[': VIOLET
  '\': PURPLE
effect-keybinds:
  a:
    effect: EffectStrobe
    name: STROBE
    colors: [RANDOM]
    options:
      lights-per-segment: 64
      color-mode: PER_SEGMENT
      segments-per-flash: 1
      frequency: 15 #in HZ
      strobe-on-mult: 0.5
  s:
    effect: EffectStrobe
    name: STROBE
    colors: [WHITE]
    options:
      lights-per-segment: 64
      color-mode: PER_SEGMENT
      segments-per-flash: 1
      frequency: 15 #in HZ
      strobe-on-mult: 0.5
  d:
    effect: EffectMitchellVisualizer
    name: VISUALIZER
    colors: [RANDOM, RANDOM]
  f:
    effect: EffectChasers
    name: RANDOM CHASERS
    colors: [RED, GREEN]
    options:
      num-chasers: 15
      min-length: 8
      max-length: 18
      min-velocity: 15
      max-velocity: 25
      tail-alpha: 0.2
  g:
    effect: EffectRainbowPulse
    name: RAINBOW PULSE
    colors: [RANDOM]
  h:
    effect: EffectFlashSegments
    name: FLASH SEGMENTS
    colors: [RANDOM, RANDOM]
    options:
      segments-per-flash: 2
      duration-factor: 2
  i:
    effect: EffectBuildup
    name: ILLUMINATE
    colors: [WHITE]
  j:
    effect: EffectFlicker
    name: FLICKER
    colors: [ffdc96, ffc157, ffec80]
  k:
    effect: EffectNeoVisualizerLogAverages
    name: NEOVISUALIZER
    colors: [RANDOM]
  l:
    effect: EffectNeoVisualizer
    name: NEOVISUALIZER
    colors: [RANDOM]
    options:
      colorChangeSpeed: 10
      divisionsPerBand: 2
      minBeatFreq: 25
      maxBeatFreq: 65
      beatDelay: 200
      doBeatFlash: true
  x:
    effect: EffectNull
    name: NULL EFFECT
    colors: [RED, GREEN]


#  a:
#    name: EffectVisualizer
#    options: [0]
#    colors: [RED, ORANGE, YELLOW]
#  s:
#    name: EffectChasers
#    options:
#      speed: 20
#      count: 10
#      length: 5
#    colors: [-1]
#  d:
#    name: EffectPulsers
##    options: [6, 9, 5]
#    opti
#    colors: [GOLD, PURPLE]
#  f:
#    name: EffectFlashSegments
#    options: [2, 1]
#    colors: [-1]
#  g:
#    name: EffectStrobe
#    options: [0]
#    colors: [WHITE]
